In [5]:
import numpy as np

In [9]:
a = np.array([1,2.5,3,4,5])
print(a)
a

[1.  2.5 3.  4.  5. ]


array([1. , 2.5, 3. , 4. , 5. ])

In [12]:
b = np.arange(10)
b.ndim # provide the array dimention 

1

In [22]:
c = np.array([[1,2],[3,4],[5,2]])
print(c)
print(c.ndim)
print(c.size)
type(c)



[[1 2]
 [3 4]
 [5 2]]
2
6


numpy.ndarray

In [24]:
d = np.arange(30).reshape(6,5)
print(d)
print(d.ndim)
print(d.size)
type(d)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
2
30


numpy.ndarray

In [28]:
e = np.zeros([3,2])
e


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.random.random((2,5))




array([[0.36943852, 0.91583384, 0.33315691, 0.05639896, 0.44228817],
       [0.39685662, 0.02266911, 0.83850248, 0.0751425 , 0.60174178]])

In [38]:
np.floor(100*np.random.random((2,5)))

array([[79., 14., 61., 73., 78.],
       [ 7., 28., 93., 46., 88.]])

In [39]:
np.ceil(100*np.random.random((2,5)))

array([[83., 69., 30., 47., 91.],
       [75., 98., 19., 45., 83.]])

In [45]:
np.floor(10.7)

10.0

In [41]:
np.ceil(10.4)

11.0

In [68]:
m = np.floor(100*np.random.random((4,6)))
m

array([[23., 10., 13., 26., 72., 30.],
       [56., 18., 79., 59., 45., 78.],
       [80., 15., 69., 68., 29., 96.],
       [20., 39., 75., 94., 66., 68.]])

In [69]:
np.hsplit(m,2)

[array([[23., 10., 13.],
        [56., 18., 79.],
        [80., 15., 69.],
        [20., 39., 75.]]), array([[26., 72., 30.],
        [59., 45., 78.],
        [68., 29., 96.],
        [94., 66., 68.]])]

In [70]:
np.vsplit(m,2)


[array([[23., 10., 13., 26., 72., 30.],
        [56., 18., 79., 59., 45., 78.]]),
 array([[80., 15., 69., 68., 29., 96.],
        [20., 39., 75., 94., 66., 68.]])]

In [72]:
q = m.copy()
q

array([[23., 10., 13., 26., 72., 30.],
       [56., 18., 79., 59., 45., 78.],
       [80., 15., 69., 68., 29., 96.],
       [20., 39., 75., 94., 66., 68.]])