# Numpy Tutorial

In [2]:
#Importing Numpy package
import numpy as np


In [5]:
#Declaring simple array
a = np.array([2,3,4,6,2])
a

array([2, 3, 4, 6, 2])

In [6]:
#Initiating static two dimensional array
b = np.array([[2,3,4,6,2],[4,5,6,9,4]])
print(b)

[[2 3 4 6 2]
 [4 5 6 9 4]]


In [7]:
# ndim parameter to get dimension of array
b.ndim

2

In [8]:
#array shape parameter to get shape of the array
a.shape

(5,)

In [11]:
print(a)

array([[2, 3, 4, 6, 2],
       [4, 5, 6, 9, 4]])

In [15]:
#dtype parameter to get type of array
type(b)
b.dtype

dtype('int64')

In [16]:
# auto type casting to higher data types as Array is homogenous
c = np.array([2,3,4.2,6,2])
c

array([ 2. ,  3. ,  4.2,  6. ,  2. ])

In [18]:
#Checking auto typecasting
c.dtype


dtype('float64')

In [17]:
#string can be auto typecasted as well.
b = np.array([6, 7, 8.0,'a'])
print(b)

['6' '7' '8.0' 'a']


In [ ]:
# array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

In [7]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ], dtype=int )
c

array([[1, 2],
       [3, 4]])

In [19]:
#The function zeros creates an array full of zeros
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [37]:
#arange function to create sequential array
data = np.arange(30)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
#reshape function to reshape array to the required dimension
data= data.reshape(6,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
#more reshape examples
data1 = np.arange(10,100,5).reshape(6,3)
data2 = np.arange(110,200,5).reshape(6,3)
data1

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80],
       [85, 90, 95]])

In [21]:
data3= np.arange(18).reshape(6,3)
data3**15

array([[                  0,                   1,               32768],
       [           14348907,          1073741824,         30517578125],
       [       470184984576,       4747561509943,      35184372088832],
       [    205891132094649,    1000000000000000,    4177248169415651],
       [  15407021574586368,   51185893014090757,  155568095557812224],
       [ 437893890380859375, 1152921504606846976, 2862423051509815793]])

In [3]:
#creating array for spliting examples
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
#horizontal splititing
a_hsplit = np.hsplit(a,2)
a_hsplit

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [6]:
#Vertical split
a_vsplit=np.vsplit(a,2)
a_vsplit

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [7]:
#creating arrays for stacking examples
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [58]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [63]:
#combing arrays with vertical stacking
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
#combing arrays with hozontal stacking
np.hstack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [32]:
#universal functions such as sqrt, sin, cos etc.,
print("Pi constant value : ",np.pi)  # pi constant
d = np.arange(0,120,30).reshape(2,2)  # array to apply sin cos
print("d array with angles in degrees")
print(d)
d_rad = d*np.pi/180 # converted angles to radians
print("d array with angles in radians")
print(d_rad)
print("Sin values of angles 0,30,60,90")
print(np.sin(d_rad))
print("Square root function on array")
e = np.array([4,9,16,25])
np.sqrt(e)

Pi constant value :  3.141592653589793
d array with angles in degrees
[[ 0 30]
 [60 90]]
d array with angles in radians
[[ 0.          0.52359878]
 [ 1.04719755  1.57079633]]
Sin values of angles 0,30,60,90
[[ 0.         0.5      ]
 [ 0.8660254  1.       ]]
Square root function on array


array([ 2.,  3.,  4.,  5.])

In [40]:
#Numpy is capable of  huge Arrays manuplation very efficiently
a = np.arange(9000000).reshape(9000,1000)
a


array([[      0,       1,       2, ...,     997,     998,     999],
       [   1000,    1001,    1002, ...,    1997,    1998,    1999],
       [   2000,    2001,    2002, ...,    2997,    2998,    2999],
       ..., 
       [8997000, 8997001, 8997002, ..., 8997997, 8997998, 8997999],
       [8998000, 8998001, 8998002, ..., 8998997, 8998998, 8998999],
       [8999000, 8999001, 8999002, ..., 8999997, 8999998, 8999999]])

In [28]:
#shape manuplation
a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print(a)
print(b)


[[0 1]
 [2 3]]
[[11 12]
 [13 14]]


In [42]:
#Generating random number with Numpy. random number are between 0 and 1
np.random.random()

0.34133393425840974

#### Random number functions in numpy.random
rand(d0, d1, …, dn)	Random values in a given shape. <br\>
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.<br\>
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).<br\>
random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.<br\>
random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
random([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
ranf([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
sample([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array<br\>
bytes(length)	Return random bytes.


In [49]:
print("Random numbers with required shape")
print(np.random.rand(3,2))
print("random integers betweet two numbers with required size")
print(np.random.randint(10,50,10))

Random numbers with required shape
[[ 0.47835435  0.24217288]
 [ 0.28590123  0.24157521]
 [ 0.48397795  0.86400097]]
random integers betweet two numbers with required size
[38 19 31 20 45 33 11 44 29 45]


In [52]:
#Numpy floor, ceil and round
print(np.floor(5.9))
print(np.ceil(3.3))
print(np.round(4.7))


5.0
4.0
5.0


In [64]:
#Copies and Views

# No Copy at All¶

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
b = a            # no new object is created
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
a[5] = 160
a

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [67]:
b

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [ ]:
b.shape = 3,4    # changes the shape of a.shape(3, 4)

In [ ]:
a.shape

In [ ]:
c.base is a  
a.shape
a

In [ ]:
c.shape = 2,6                      # a's shape doesn't change
print(a.shape)
c

In [ ]:
c[0,4] = 999                    # a's data changes
c

In [ ]:
a

In [59]:
# Deep Copy

b = a.copy() 


In [61]:
a[4] = 234
a

array([  0,   1,   2,   3, 234, 160,   6,   7,   8,   9,  10,  11])

In [62]:
b

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

## This completes basic tutorial on Numpy package