# NUMPHY (Numerical Phython) Tutorial

In [2]:
import numpy as np

# Array
### Array are Homogeneous ( It can have only one type on values), Automatic convert to higher type
### Can't have inconsistent elements numbers( for two dimension array all array must have same number of elements


In [3]:

# One dimension Array

a = np.array([1,2,3,4,4,5,5,5,9])
a
print(a)
print(a.ndim)
print("Array: ", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))


[1 2 3 4 4 5 5 5 9]
1
Array:  [1 2 3 4 4 5 5 5 9]
N-Dimension :  1
Array-Shape (9,)
Size :  9
Element Data Type:  int32
Data Type:  <class 'numpy.ndarray'>


In [4]:
# Two Dimension Array
a = np.array([
              [1,2,5,6],
              [1,3,5,9]
             ])
a
print(a)
print("Array: ", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))


[[1 2 5 6]
 [1 3 5 9]]
Array:  [[1 2 5 6]
 [1 3 5 9]]
N-Dimension :  2
Array-Shape (2, 4)
Size :  8
Element Data Type:  int32
Data Type:  <class 'numpy.ndarray'>


In [5]:
### Array are Homogeneous ( It can have only one type on values), Automatic convert to higher type

aa = np.array([1,2,3,4,4,5,5,5,9])
aa.dtype


aa = np.array([1,2,3,4,4,5,5,5,'Rakesh'])
type(aa)

### Can't have inconsistent elements numbers( for two dimension array all array must have same number of elements
#a = np.array([
#              [1,2,5,6],
#              [1,3,5,9,4,6]
#             ])
#a
#print("N-Dimension : ", a.ndim)

numpy.ndarray

# 3 Dimension Array

In [6]:
# Two Dimension Array
a = np.array([
              [
                [1,2,5,6],[1,3,5,9],[2,2,5,9]
              ],
              [
                [1,4,2,6], [1,3,8,3],[8,5,5,9]
              ]
             ])
print("Array: \n", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))


Array: 
 [[[1 2 5 6]
  [1 3 5 9]
  [2 2 5 9]]

 [[1 4 2 6]
  [1 3 8 3]
  [8 5 5 9]]]
N-Dimension :  3
Array-Shape (2, 3, 4)
Size :  24
Element Data Type:  int32
Data Type:  <class 'numpy.ndarray'>


In [7]:
a[1][0][1]

4

In [8]:
print(a[1])
print(a[1][1])
print(a[1][1][2])


[[1 4 2 6]
 [1 3 8 3]
 [8 5 5 9]]
[1 3 8 3]
8


## Array Range Function
## np.arange() 

In [15]:
# it generate an array from 0 to 9 
a = np.arange(10)

print("Array: \n", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))


Array: 
 [0 1 2 3 4 5 6 7 8 9]
N-Dimension :  1
Array-Shape (10,)
Size :  10
Element Data Type:  int32
Data Type:  <class 'numpy.ndarray'>


In [16]:
# Provide start and stop point
# arange(startPoint, stopPoint)
a = np.arange(10,20)


print("Array: \n", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))


Array: 
 [10 11 12 13 14 15 16 17 18 19]
N-Dimension :  1
Array-Shape (10,)
Size :  10
Element Data Type:  int32
Data Type:  <class 'numpy.ndarray'>


In [17]:
# Provide arange(start, stop, step)
a = np.arange(10,50,5)


print("Array: \n", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
#print("Data Type: ", type(a))


Array: 
 [10 15 20 25 30 35 40 45]
N-Dimension :  1
Array-Shape (8,)
Size :  8
Element Data Type:  int32


In [28]:
# linspace (start, stop, number of elements)
# means it distribute array in equal number of parts as given number

a = np.linspace(10, 50, 5)


print("Array: \n", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))



Array: 
 [10. 20. 30. 40. 50.]
N-Dimension :  1
Array-Shape (5,)
Size :  5
Element Data Type:  float64
Data Type:  <class 'numpy.ndarray'>


# np.reshape(x,y,z,..)

In [18]:
# reshape()
# means recreate the array in new shape or dimensions

a = np.arange(20)
print(a)

a = a.reshape(4,5)
#a = np.arange(20).reshape(2,10)

print("Array: \n", a )
print("N-Dimension : ", a.ndim)
print("Array-Shape", a.shape)
print("Size : ", a.size)
print("Element Data Type: " , a.dtype)
print("Data Type: ", type(a))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
N-Dimension :  2
Array-Shape (4, 5)
Size :  20
Element Data Type:  int32
Data Type:  <class 'numpy.ndarray'>


## np.ravel() ( Opposite of reshape, it comvert any array in to single array

In [20]:
# ravel() -> keep all elements adding in single array
# it will not sort elements.

a.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# np.random.rand() ( generate random number between 0 to 1

In [21]:
# Generate random number
np.random.rand()

0.2207392481377758

In [25]:
# Create an array of random double elements (row, columns)

np.random.rand(4,5)

array([[0.22153585, 0.46706791, 0.64783923, 0.55961554, 0.82302499],
       [0.82368752, 0.88906698, 0.26055491, 0.2494199 , 0.74773907],
       [0.40691341, 0.26563912, 0.74393129, 0.82975624, 0.56198571],
       [0.48783543, 0.86819844, 0.58565146, 0.57098817, 0.51455329]])

# np.random.randint(start, stop, number of element) 

In [29]:
# Create an array of random integer elements betwnn the given range
# randint(minNumber, maxNumber, numberOfelementToSelect)

np.random.randint(3,7)

3

In [30]:
# Create an array of random integer elements ARRAY betwnn the given range
# randint(minNumber, maxNumber, numberOfelementToSelect)

np.random.randint(10,50,20)

array([21, 36, 47, 25, 22, 21, 42, 18, 33, 46, 47, 16, 24, 26, 41, 15, 18,
       43, 35, 33])

In [47]:
np.random.randint(10,50,20).reshape(4,5)

array([[14, 47, 35, 31, 44],
       [41, 44, 36, 45, 18],
       [26, 14, 17, 18, 11],
       [41, 39, 43, 19, 33]])

# Numpy stacking and splitting
## np.hstack((arrayA, arrayB)) -> #( Horizontal means X -> axis)
## np.vstack((arrayA, arrayB)) -> #( Vertical means Y -> axis)

In [31]:
a = np.random.randint(1, 100, 12).reshape(3,4)
b = np.random.randint(1, 100, 12).reshape(3,4)
print("a array: " , a)
print("b array: " , b)



a array:  [[24 90 80 39]
 [58 19 31  1]
 [16 29 95 96]]
b array:  [[49 13  2 25]
 [56  5 88 92]
 [41 29 79 72]]


In [32]:
np.hstack((a, b)) 

#( Horizontal means X -> axis)

array([[24, 90, 80, 39, 49, 13,  2, 25],
       [58, 19, 31,  1, 56,  5, 88, 92],
       [16, 29, 95, 96, 41, 29, 79, 72]])

In [60]:
# split horizontal

a_splitted = np.hsplit(a, 2)
print(a_splitted)
print(a_splitted[0])


[array([[22, 81],
       [57, 55],
       [ 9, 23]]), array([[21, 32],
       [80, 75],
       [94, 64]])]
[[22 81]
 [57 55]
 [ 9 23]]


In [ ]:
# Split vertical

In [62]:
np.vstack(( a, b)) 
a_splitted = np.vsplit(a, 3)
print(a_splitted)
print(a_splitted[0])

# (Vertical means Y -> axis)

[array([[22, 81, 21, 32]]), array([[57, 55, 80, 75]]), array([[ 9, 23, 94, 64]])]
[[22 81 21 32]]


# Deep copy OR Copy element 

In [64]:
a = np.random.randint(1, 100, 12).reshape(3,4)
print("a array: " , a)

z = a.copy()
z


a array:  [[70  2 44 56]
 [66 91 30 45]
 [99 19 43 88]]


array([[70,  2, 44, 56],
       [66, 91, 30, 45],
       [99, 19, 43, 88]])

# np.matmul()
## used for the multiplicaiton in array (row[] * col[])

In [69]:
a = np.random.randint(1, 100, 9).reshape(3,3)
b = np.random.randint(1, 100, 9).reshape(3,3)
print("a array: " , a)
print("b array: " , b)

np.matmul(a,b)


a array:  [[38 37 31]
 [86 15 96]
 [ 6 15 80]]
b array:  [[94  4 61]
 [59 31 37]
 [59 33 35]]


array([[ 7584,  2322,  4772],
       [14633,  3977,  9161],
       [ 6169,  3129,  3721]])

# floor(), ceil(), round() works on the all elements of the array

In [81]:
np.floor(5.4) # return min

5.0

In [82]:
np.ceil(5.4) # return max

6.0

In [79]:
np.round(5.4) # return rouned number

5.0

In [83]:
np.round(5.6)

6.0

In [84]:
np.floor(np.random.rand(2,3)*10)

array([[9., 8., 9.],
       [1., 7., 1.]])

In [86]:
# Squar root of 

np.sqrt(2)

1.4142135623730951

In [87]:
np.sqrt(np.random.rand(2,3)*10)

array([[2.09752148, 0.94261746, 3.15967982],
       [1.00214169, 2.2531811 , 2.08881498]])

In [ ]:
#