# Numpy Tutorial

In [1]:
#Importing Numpy package
import numpy as np


In [7]:
a = np.array([3.1,4,6,8])
print(a)
print(a.ndim)
print(type(a))
print(a.dtype)

[ 3.1  4.   6.   8. ]
1
<class 'numpy.ndarray'>
float64


In [12]:
b = np.array([[[2,4,9],[3,6,7]],
              [[6,8,10],[13,16,17]],
             [[12,14,19],[23,26,27]]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[[ 2  4  9]
  [ 3  6  7]]

 [[ 6  8 10]
  [13 16 17]]

 [[12 14 19]
  [23 26 27]]]
3
(3, 2, 3)
int64


In [6]:
#Declaring simple array
a = np.array([[3,7,2,9],[9,12,15]])
print(type(a))
a

<class 'numpy.ndarray'>


array([[3, 7, 2, 9], [9, 12, 15]], dtype=object)

In [7]:
a.shape

(2,)

In [4]:
b = np.array([[[3,4],[2,4],[2,6]],
              [[3,80],[2,100],[2,6]],
              [[3,78],[2,44],[2,90]]])
b.shape

(3, 3, 2)

In [8]:
b[2][1][1]

44

In [24]:
b.ndim

3

In [15]:
a.shape

(4,)

In [16]:
a.ndim

1

In [11]:
#Initiating static two dimensional array
b = np.array([[2,3,4,6,2],[4,5,6,9,4],[4,5,6,9,4]])
print(b)

[[2 3 4 6 2]
 [4 5 6 9 4]
 [4 5 6 9 4]]


In [6]:
# ndim parameter to get dimension of array
b.ndim

2

In [12]:
b.shape

(3, 5)

In [7]:
c = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])

In [9]:
print(c)

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]


In [11]:
#array shape parameter to get shape of the array
b.shape

(3, 5)

In [11]:
print(a)

array([[2, 3, 4, 6, 2],
       [4, 5, 6, 9, 4]])

In [15]:
#dtype parameter to get type of array
type(b)
b.dtype

dtype('int64')

In [30]:
# auto type casting to higher data types as Array is homogenous
c = np.array([2,3,4.2,6,2])
c.dtype

dtype('float64')

In [13]:
type(b)

numpy.ndarray

In [12]:
b.dtype

dtype('int64')

In [18]:
#Checking auto typecasting
c.dtype


dtype('float64')

In [17]:
#string can be auto typecasted as well.
b = np.array([6, 7, 8.0,'a'])
print(b)

['6' '7' '8.0' 'a']


In [ ]:
# array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

In [7]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ], dtype=int )
c

array([[1, 2],
       [3, 4]])

In [19]:
#The function zeros creates an array full of zeros
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.array([2,4.0,5])

array([2., 4., 5.])

In [24]:
c = np.arange(100,200,5).reshape(2,2,5)
print(c)
print(c.shape)

[[[100 105 110 115 120]
  [125 130 135 140 145]]

 [[150 155 160 165 170]
  [175 180 185 190 195]]]
(2, 2, 5)


In [28]:
c.ravel().reshape(4,5)

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [35]:
np.linspace(100,200,5)

array([ 100.,  125.,  150.,  175.,  200.])

In [43]:
np.random.rand(3,4)

array([[ 0.28007835,  0.21547088,  0.38438464,  0.81349463],
       [ 0.52592545,  0.15204815,  0.00573051,  0.76025747],
       [ 0.15820986,  0.8703204 ,  0.82512008,  0.28245109]])

In [47]:
np.random.randint(10,50,15).reshape(5,3)

array([[42, 15, 16],
       [28, 15, 17],
       [21, 30, 16],
       [24, 34, 34],
       [41, 40, 35]])

In [53]:
a = [3,4,5]
b=a.copy()

In [54]:
a[2]=500
a

[3, 4, 500]

In [55]:
b

[3, 4, 5]

In [36]:
#arange function to create sequential array
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
data = np.arange(10,20,2)
data

array([10, 12, 14, 16, 18])

In [43]:
np.arange(12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
data = np.arange(100,200,5).reshape(2,2,5)
data

array([[[100, 105, 110, 115, 120],
        [125, 130, 135, 140, 145]],

       [[150, 155, 160, 165, 170],
        [175, 180, 185, 190, 195]]])

In [24]:
data.shape

(2, 2, 5)

In [25]:
data.ravel()

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [30]:
data1 = np.linspace(10,100,20)
data1

array([  10.        ,   14.73684211,   19.47368421,   24.21052632,
         28.94736842,   33.68421053,   38.42105263,   43.15789474,
         47.89473684,   52.63157895,   57.36842105,   62.10526316,
         66.84210526,   71.57894737,   76.31578947,   81.05263158,
         85.78947368,   90.52631579,   95.26315789,  100.        ])

In [44]:
data2 = np.round(100*np.random.rand(10).reshape(2,5))
data2

array([[ 30.,  39.,  53.,  82.,  70.],
       [ 33.,  49.,  67.,  40.,  44.]])

In [40]:
data3 = np.random.randint(50,100,15).reshape(3,5)
data3

array([[54, 66, 67, 95, 82],
       [74, 63, 68, 87, 86],
       [72, 61, 50, 89, 82]])

In [38]:
#reshape function to reshape array to the required dimension
data= data.reshape(6,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
np.arange(200000).reshape(20,200,50)

57735.026918240888

In [46]:
#more reshape examples
data1 = np.arange(10,100,5).reshape(6,3)
data2 = np.arange(110,200,5).reshape(6,3)
data1

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80],
       [85, 90, 95]])

In [46]:
data3= np.arange(18).reshape(6,3)
data3**153459

array([[                   0,                    1,                    0],
       [ 7226235673377750619,                    0,  2964750606344296893],
       [                   0,  4184484713180964567,                    0],
       [-5078874989110414247,                    0, -7951459236004585741],
       [                   0, -2776297176606304939,                    0],
       [-3768903304874693585,                    0, -5677463112146214351]])

In [47]:
#creating array for spliting examples
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
#horizontal splititing
a_hsplit = np.hsplit(a,4)
a_hsplit[3]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [53]:
#Vertical split
a_vsplit=np.vsplit(a,2)
a_vsplit[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
#creating arrays for stacking examples
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [62]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
#combing arrays with vertical stacking
np.hstack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [64]:
#combing arrays with hozontal stacking
np.hstack((a,b))

array([[ 0,  1,  2, 16, 17, 18, 19],
       [ 3,  4,  5, 20, 21, 22, 23],
       [ 6,  7,  8, 24, 25, 26, 27],
       [ 9, 10, 11, 28, 29, 30, 31]])

In [68]:
#universal functions such as sqrt, sin, cos etc.,
print("Pi constant value : ",np.pi)  # pi constant
d = np.arange(0,120,30).reshape(2,2)  # array to apply sin cos
print("d array with angles in degrees")
print(d)
d_rad = d*np.pi/180 # converted angles to radians
print("d array with angles in radians")
print(d_rad)
print("Sin values of angles 0,30,60,90")
print(np.sin(d_rad))
print("Square root function on array")
e = np.array([4,9,16,25])
np.sqrt(e)

Pi constant value :  3.141592653589793
d array with angles in degrees
[[ 0 30]
 [60 90]]
d array with angles in radians
[[ 0.          0.52359878]
 [ 1.04719755  1.57079633]]
Sin values of angles 0,30,60,90
[[ 0.         0.5      ]
 [ 0.8660254  1.       ]]
Square root function on array


array([ 2.,  3.,  4.,  5.])

In [40]:
#Numpy is capable of  huge Arrays manuplation very efficiently
a = np.arange(9000000).reshape(9000,1000)
a

array([[      0,       1,       2, ...,     997,     998,     999],
       [   1000,    1001,    1002, ...,    1997,    1998,    1999],
       [   2000,    2001,    2002, ...,    2997,    2998,    2999],
       ..., 
       [8997000, 8997001, 8997002, ..., 8997997, 8997998, 8997999],
       [8998000, 8998001, 8998002, ..., 8998997, 8998998, 8998999],
       [8999000, 8999001, 8999002, ..., 8999997, 8999998, 8999999]])

In [28]:
#shape manuplation
a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print(a)
print(b)


[[0 1]
 [2 3]]
[[11 12]
 [13 14]]


In [46]:
#Generating random number with Numpy. random number are between 0 and 1
int(50+np.random.random()*10)
# min+rand*(max-min)

52

In [ ]:
#### Random number functions in numpy.random
rand(d0, d1, …, dn)	Random values in a given shape. <br\>
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.<br\>
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).<br\>
random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.<br\>
random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
random([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
ranf([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
sample([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array<br\>
bytes(length)	Return random bytes.


In [77]:
np.random.random_integers(100,200,20).reshape(4,5)

/Users/ashok/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(100, 200 + 1) instead
  """Entry point for launching an IPython kernel.


array([[141, 145, 182, 133, 161],
       [152, 108, 178, 155, 130],
       [174, 140, 176, 153, 174],
       [131, 115, 159, 127, 121]])

In [80]:
np.random.randint(100,200,20)

array([129, 177, 141, 164, 126, 158, 101, 182, 175, 119, 103, 181, 193,
       161, 178, 114, 194, 193, 107, 190])

In [72]:
np.random.rand(2,2,3)

array([[[ 0.70772871,  0.52909109,  0.65347911],
        [ 0.96970424,  0.04034972,  0.82230787]],

       [[ 0.35640307,  0.79552466,  0.54278039],
        [ 0.53440244,  0.84037298,  0.42575122]]])

In [69]:
print("Random numbers with required shape")
print(np.random.rand(3,2))
print("random integers betweet two numbers with required size")
print(np.random.randint(10,50,100))

Random numbers with required shape
[[ 0.69134577  0.72954293]
 [ 0.51638422  0.24177468]
 [ 0.34793011  0.52396093]]
random integers betweet two numbers with required size
[17 41 49 37 41 35 43 42 22 36 15 10 20 41 22 26 14 18 45 13 21 42 33 24 40
 10 49 32 34 13 40 21 35 34 16 32 20 30 25 36 38 28 15 41 48 38 24 12 23 43
 27 34 37 43 17 48 20 33 14 45 32 30 13 28 14 45 34 45 49 13 14 47 14 30 46
 10 19 24 20 42 46 48 26 17 24 43 41 38 22 45 13 20 41 47 21 34 27 35 17 34]


In [81]:
#Numpy floor, ceil and round
print(np.floor(5.9))
print(np.ceil(3.3))
print(np.round(4.3))


5.0
4.0
4.0


In [84]:
np.floor((np.random.rand(20).reshape(4,5)*100))

array([[ 16.,  10.,   2.,  59.,  48.],
       [ 59.,  82.,  19.,  74.,  62.],
       [ 74.,  28.,  21.,  87.,   8.],
       [ 79.,  23.,  56.,  96.,  46.]])

In [68]:
#Copies and Views

# No Copy at All¶

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [69]:
b = a          # no new object is created
b

array([0, 1, 2, 3, 4, 5])

In [71]:
a[5] = 160
a

array([  0,   1,   2,   3,   4, 160])

In [72]:
b = a.copy()

array([  0,   1,   2,   3,   4, 160])

In [ ]:
b.shape = 3,4    # changes the shape of a.shape(3, 4)

In [ ]:
a.shape

In [ ]:
c.base is a  
a.shape
a

In [ ]:
c.shape = 2,6                      # a's shape doesn't change
print(a.shape)
c

In [ ]:
c[0,4] = 999                    # a's data changes
c

In [ ]:
a

In [59]:
# Deep Copy

b = a.copy() 


In [61]:
a[4] = 234
a

array([  0,   1,   2,   3, 234, 160,   6,   7,   8,   9,  10,  11])

In [62]:
b

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [102]:
data = np.linspace(10,20,10)
data

array([ 10.        ,  11.11111111,  12.22222222,  13.33333333,
        14.44444444,  15.55555556,  16.66666667,  17.77777778,
        18.88888889,  20.        ])

In [58]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [103]:
a = [[1,2],[1,3]]
b = [[4,2],[1,3]]

In [104]:
np.matmul(a,b)

array([[ 6,  8],
       [ 7, 11]])

## This completes basic tutorial on Numpy package